### ISSUE TITLE
not a static linked binary, requires specific versions of libc etc.

### ISSUE THREAD

**Issue by sling00** [Optiminer/OptiminerZcash#3]
Ubuntu 14.04.5 LTS: 

./optiminer-zcash: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./optiminer-zcash)

Please static link the binary so that it will work across multiple linux versions instead of being locked to 16.04

**Comment by Singman33** [comment]
And I dont like closed source programs posted on Github. Either you release sources, either you remove it from that place.

**Comment by ddobreff** [comment]
Agree,
The chance to debug is 100% more efficent when the code is opened.

**Comment by Singman33** [comment]
Look like that miner have **hidden dev fees**, a lot more than anyone else.

**Comment by rbrtio** [comment]
The dev fee isn't hidden, it was mentioned in the posts on both bitcoinalk and zcash forum.

The hash rate displayed by the miner takes into account the dev fee.  You can validate this by checking your pool statistics.

If you can create a miner that provides a 30% improvement over anything else available, I will gladly pay you the 15% dev fee instead.

**Comment by Singman33** [comment]
Ahahah what a joke ! You put a program with a fee that hide this part on the log file, you dont even write a note on the README (that should always be joined with the program), and you think you are not lying to users ?
30% gain against what ? nheqminer ? Wrong ! Silentarmy ? Wrong ! The improvement is less than 15% over theses two, and one of them is full open source with no fee (and you know that because I traced some common kernel code in common with it), and the other is  locked on a pool (Nicehash).

Instead of using that piece of crap, go to a full open source program and stop giving your money to theives.

**Comment by rbrtio** [comment]
First of all, I'm a user not the dev, so get that correct.

For me, it wa a 30% gain from SA v5 to this, my 6 X RX 470 4GB cards were generating 482H/s on SA and on this they generate about 640H/s. that is an increase of 32.78%.  Simple math.

I will chose to do what I think is best for me and I expect you will do the same.

**Comment by Optiminer** [comment]
The newest version is now statically linked against libstdc++.
